### ISSUE TITLE
reloadtimeout not working

### ISSUE THREAD

**Issue by niraj2477** [Arrilot/laravel-widgets#141] opened 2020-06-04 09:12 UTC
first of all its nice package. working fine almost . im facing problem with reloadtimeout and asyncwidget it is not working

this is my code

<?php

namespace App\Widgets;
use DB;
use Arrilot\Widgets\AbstractWidget;

class Registrationdata extends AbstractWidget
{
    /**
     * The configuration array.
     *
     * @var array
     */
 
    public $reloadTimeout = 5;
    protected $config = [];
    public function placeholder()
    {
        return 'Loading...';
    }
    /**
     * Treat this method as a controller action.
     * Return view() or other content to display.
     */
    public function run()
    {
        //
        $data=DB::table('registrations_masterTable')->where('status','=',0)->get();
        return view('widgets.registrationdata', [
            'config' => $this->config,
            'data'=>$data
        ]);
    }
}

**Comment by kerwin0831** [comment] 2020-06-11 04:59
I got the same problem

**Comment by arrilot** [comment] 2020-09-20 19:01
Duplicate of #137 137

**Closed as completed by arrilot** 2020-09-20 19:01 UTC
